from __future__ import annotations
import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone

import numpy as np

from . import config

SCHEMA = """
CREATE TABLE IF NOT EXISTS papers (
    arxiv_id TEXT PRIMARY KEY,
    version INTEGER DEFAULT 1,
    title TEXT NOT NULL,
    abstract TEXT NOT NULL,
    authors TEXT DEFAULT '[]',
    categories TEXT DEFAULT '[]',
    published TEXT,
    updated TEXT,
    tldr TEXT,
    tags TEXT,
    task TEXT,
    method TEXT,
    embedding BLOB,
    interpretation TEXT,
    interpreted_at TEXT,
    fetched_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_papers_published ON papers(published DESC);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    arxiv_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    value REAL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_paper ON events(arxiv_id);
CREATE INDEX IF NOT EXISTS idx_events_kind ON events(kind);

CREATE TABLE IF NOT EXISTS searches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    topic TEXT NOT NULL,
    query TEXT,
    label TEXT,
    months INTEGER,
    created_at TEXT NOT NULL,
    total INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS search_results (
    search_id INTEGER NOT NULL,
    arxiv_id TEXT NOT NULL,
    position INTEGER NOT NULL,
    PRIMARY KEY (search_id, arxiv_id)
);
CREATE TABLE IF NOT EXISTS prefs (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""

# Columns added after the first release; applied with ALTER TABLE when missing.
PAPER_EXTRA_COLUMNS = [
    ("citation_count", "INTEGER"),
    ("venue", "TEXT"),
    ("affiliations", "TEXT"),
    ("affil_score", "INTEGER"),
]
EXTRA_COLUMNS = {
    "papers": PAPER_EXTRA_COLUMNS,
    "searches": [("intent", "TEXT")],
    "search_results": [("relevance", "INTEGER")],
}


def utcnow() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


@contextmanager
def get_conn():
    conn = sqlite3.connect(config.DB_PATH, timeout=30)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=30000")
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db():
    with get_conn() as conn:
        conn.executescript(SCHEMA)
        for table, columns in EXTRA_COLUMNS.items():
            existing = {r[1] for r in conn.execute(f"PRAGMA table_info({table})")}
            for col, typ in columns:
                if col not in existing:
                    conn.execute(f"ALTER TABLE {table} ADD COLUMN {col} {typ}")


def upsert_papers(papers) -> int:
    """Insert new papers; update title/abstract when a newer version appears. Returns count of new rows."""
    new = 0
    with get_conn() as conn:
        for p in papers:
            row = conn.execute(
                "SELECT version FROM papers WHERE arxiv_id = ?", (p["arxiv_id"],)
            ).fetchone()
            if row is None:
                conn.execute(
                    "INSERT INTO papers (arxiv_id, version, title, abstract, authors, categories,"
                    " published, updated, fetched_at) VALUES (?,?,?,?,?,?,?,?,?)",
                    (
                        p["arxiv_id"],
                        p["version"],
                        p["title"],
                        p["abstract"],
                        json.dumps(p["authors"], ensure_ascii=False),
                        json.dumps(p["categories"]),
                        p["published"],
                        p["updated"],
                        utcnow(),
                    ),
                )
                new += 1
            elif p["version"] > (row["version"] or 1):
                # A new version changes the abstract, so everything derived from it
                # must be regenerated by the same pipeline run.
                conn.execute(
                    "UPDATE papers SET version=?, title=?, abstract=?, updated=?,"
                    " tldr=NULL, tags=NULL, task=NULL, method=NULL, embedding=NULL,"
                    " interpretation=NULL, interpreted_at=NULL WHERE arxiv_id=?",
                    (p["version"], p["title"], p["abstract"], p["updated"], p["arxiv_id"]),
                )
    return new


def pending_summaries(limit: int = 2000):
    with get_conn() as conn:
        return conn.execute(
            "SELECT arxiv_id, title, abstract, authors FROM papers WHERE tldr IS NULL"
            " ORDER BY published DESC LIMIT ?",
            (limit,),
        ).fetchall()


def pending_embeddings(limit: int = 20000):
    with get_conn() as conn:
        return conn.execute(
            "SELECT arxiv_id, title, abstract, tags, task, method FROM papers"
            " WHERE embedding IS NULL ORDER BY published DESC LIMIT ?",
            (limit,),
        ).fetchall()


def save_summary(arxiv_id: str, data: dict):
    # The embedding is built from tags/task/method too, so it must be recomputed.
    sets = "tldr=?, tags=?, task=?, method=?, embedding=NULL"
    params = [
        data.get("tldr"),
        json.dumps(data.get("tags", []), ensure_ascii=False),
        data.get("task"),
        data.get("method"),
    ]
    if "affiliations" in data:  # 精搜 batches also read labs off the first page
        sets += ", affiliations=?, affil_score=?"
        params += [json.dumps(data["affiliations"], ensure_ascii=False), int(data.get("affil_score") or 0)]
    with get_conn() as conn:
        conn.execute(f"UPDATE papers SET {sets} WHERE arxiv_id=?", params + [arxiv_id])


def save_embedding(arxiv_id: str, vector):
    save_embeddings([(arxiv_id, vector)])


def save_embeddings(pairs):
    """pairs: iterable of (arxiv_id, vector); written in one transaction."""
    with get_conn() as conn:
        conn.executemany(
            "UPDATE papers SET embedding=? WHERE arxiv_id=?",
            [(np.asarray(v, dtype=np.float32).tobytes(), a) for a, v in pairs],
        )


def save_interpretation(arxiv_id: str, text: str):
    with get_conn() as conn:
        conn.execute(
            "UPDATE papers SET interpretation=?, interpreted_at=? WHERE arxiv_id=?",
            (text, utcnow(), arxiv_id),
        )


def get_paper(arxiv_id: str):
    with get_conn() as conn:
        return conn.execute(
            "SELECT * FROM papers WHERE arxiv_id = ?", (arxiv_id,)
        ).fetchone()


def upsert_search_papers(items):
    """Insert papers found by 精搜 that we don't have yet (existing rows keep their data)."""
    now = utcnow()
    with get_conn() as conn:
        conn.executemany(
            "INSERT OR IGNORE INTO papers (arxiv_id, version, title, abstract, authors, categories,"
            " published, updated, fetched_at) VALUES (?,?,?,?,?,?,?,?,?)",
            [
                (
                    it["arxiv_id"], it.get("version") or 1, it["title"], it["abstract"],
                    json.dumps(it["authors"], ensure_ascii=False), json.dumps(it["categories"]),
                    it["published"], it["published"], now,
                )
                for it in items
            ],
        )


def set_citations(triples):
    """triples: iterable of (arxiv_id, citation_count, venue)."""
    with get_conn() as conn:
        conn.executemany(
            "UPDATE papers SET citation_count=?, venue=? WHERE arxiv_id=?",
            [(c, v, a) for a, c, v in triples],
        )


def trim_search(search_id: int, keep, total: int | None = None):
    """Re-rank a search's results to `keep` = [(arxiv_id, relevance)] order and drop the rest."""
    keep = list(keep)
    with get_conn() as conn:
        conn.execute("DELETE FROM search_results WHERE search_id = ?", (search_id,))
        conn.executemany(
            "INSERT OR IGNORE INTO search_results (search_id, arxiv_id, position, relevance) VALUES (?,?,?,?)",
            [(search_id, a, i, rel) for i, (a, rel) in enumerate(keep)],
        )
        conn.execute("UPDATE searches SET total = ? WHERE id = ?", (total if total is not None else len(keep), search_id))


def create_search(topic: str, query: str, label: str, months: int, ids, total: int, intent: str | None = None) -> int:
    with get_conn() as conn:
        cur = conn.execute(
            "INSERT INTO searches (topic, query, label, months, created_at, total, intent) VALUES (?,?,?,?,?,?,?)",
            (topic, query, label, months, utcnow(), total, intent),
        )
        search_id = cur.lastrowid
        conn.executemany(
            "INSERT OR IGNORE INTO search_results (search_id, arxiv_id, position) VALUES (?,?,?)",
            [(search_id, a, i) for i, a in enumerate(ids)],
        )
        return search_id


def get_search(search_id: int):
    with get_conn() as conn:
        meta = conn.execute("SELECT * FROM searches WHERE id = ?", (search_id,)).fetchone()
        if meta is None:
            return None, []
        rows = conn.execute(
            "SELECT p.*, s.relevance AS relevance FROM search_results s JOIN papers p ON p.arxiv_id = s.arxiv_id"
            " WHERE s.search_id = ? ORDER BY s.position",
            (search_id,),
        ).fetchall()
        return meta, rows


def papers_by_ids(ids):
    ids = list(ids)
    if not ids:
        return []
    with get_conn() as conn:
        marks = ",".join("?" * len(ids))
        return conn.execute(f"SELECT * FROM papers WHERE arxiv_id IN ({marks})", ids).fetchall()


def get_pref(key: str, default=None):
    with get_conn() as conn:
        row = conn.execute("SELECT value FROM prefs WHERE key = ?", (key,)).fetchone()
    return json.loads(row["value"]) if row else default


def set_pref(key: str, value):
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO prefs (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
            (key, json.dumps(value, ensure_ascii=False)),
        )


def saved_papers(limit: int = 200):
    """Papers whose latest save/unsave event is a save, newest first, with a liked flag."""
    with get_conn() as conn:
        return conn.execute(
            "SELECT p.*, 1 AS saved, e.created_at AS saved_at,"
            " COALESCE((SELECT l.kind FROM events l WHERE l.arxiv_id = p.arxiv_id"
            "   AND l.kind IN ('like','unlike') ORDER BY l.id DESC LIMIT 1), '') = 'like' AS liked"
            " FROM (SELECT arxiv_id, MAX(id) AS last_id FROM events"
            "       WHERE kind IN ('save','unsave') GROUP BY arxiv_id) s"
            " JOIN events e ON e.id = s.last_id AND e.kind = 'save'"
            " JOIN papers p ON p.arxiv_id = s.arxiv_id"
            " ORDER BY s.last_id DESC LIMIT ?",
            (limit,),
        ).fetchall()


def add_events(events):
    """events: iterable of (arxiv_id, kind, value)"""
    now = utcnow()
    with get_conn() as conn:
        conn.executemany(
            "INSERT INTO events (arxiv_id, kind, value, created_at) VALUES (?,?,?,?)",
            [(a, k, v, now) for a, k, v in events],
        )


def stats() -> dict:
    with get_conn() as conn:
        def one(sql):
            return conn.execute(sql).fetchone()[0]

        return {
            "papers": one("SELECT COUNT(*) FROM papers"),
            "with_tldr": one("SELECT COUNT(*) FROM papers WHERE tldr IS NOT NULL"),
            "with_embedding": one("SELECT COUNT(*) FROM papers WHERE embedding IS NOT NULL"),
            "interpreted": one("SELECT COUNT(*) FROM papers WHERE interpretation IS NOT NULL"),
            "events": one("SELECT COUNT(*) FROM events"),
            "latest_published": one("SELECT MAX(published) FROM papers"),
        }
